/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author walbonis1
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroUno = new javax.swing.JTextField();
        txtNumeroDos = new javax.swing.JTextField();
        txtResultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtResultados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbOperaciones = new javax.swing.JComboBox();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Operaciones con Dos Numerós");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Numero 1:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel1.add(txtNumeroUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, -1));
        jPanel1.add(txtNumeroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, -1));

        txtResultado.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(51, 51, 255));
        txtResultado.setText("Resultado :");
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("numero 2:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        cmdCalcular.setForeground(new java.awt.Color(255, 51, 51));
        cmdCalcular.setText("Calcular :");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        cmdBorrar.setForeground(new java.awt.Color(255, 51, 51));
        cmdBorrar.setText("Borrar :");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        txtResultados.setEditable(false);
        jPanel1.add(txtResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 110, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Operaciones:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 20));

        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suma", "Resta", "Multiplicacion", "Division" }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        cmdSalir.setFont(new java.awt.Font("Script MT Bold", 2, 24)); // NOI18N
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(501, 352));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        String res;
       double n1,n2,resultado=0;
       int op,sw=1;
       
       if(txtNumeroUno.getText().isEmpty()){
           JOptionPane.showMessageDialog (this, "digite el numero uno","error",JOptionPane.ERROR_MESSAGE);
           txtNumeroUno.requestFocusInWindow();
           sw=0;
       }
       else if (txtNumeroDos.getText().isEmpty()){
           JOptionPane.showMessageDialog (this, "digite el numero dos","error",JOptionPane.ERROR_MESSAGE);
           txtNumeroDos.requestFocusInWindow();
           sw=0;
       }else{
           try{
                n1 =Double.parseDouble(txtNumeroUno.getText());
           }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(this, "el´primer numero debe ser un numero valido","ERROR",JOptionPane.ERROR_MESSAGE);
               txtNumeroUno.requestFocusInWindow();
               txtNumeroUno.selectAll();
               sw=0;
              }

            try {
                n2 = Double.parseDouble(txtNumeroDos.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El segundo número debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                txtNumeroDos.requestFocusInWindow();
                txtNumeroDos.selectAll();
                sw = 0;
            }

        }

        if (sw == 1) {

            n1 = Double.parseDouble(txtNumeroUno.getText());
            n2 = Double.parseDouble(txtNumeroDos.getText());
            op = cmbOperaciones.getSelectedIndex();

       
         if( op == 3 && n2==0){
             JOptionPane.showMessageDialog (this, "digite el numero dos","error",JOptionPane.ERROR_MESSAGE);
           txtNumeroDos.requestFocusInWindow();
           txtNumeroDos.selectAll();
         }else{
       switch(op){
           case 0:
                   resultado=n1+n2;
               break;
           case 1:
               resultado= n1-n2;
               break;
           case 2:
               resultado=n1*n2;
               break;
           case 3:
               resultado =n1/n2;
               break;
               
       }
       
       
         }
        res =String.valueOf(resultado);
        txtResultados.setText(res);
       }
    
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        
        txtNumeroUno.setText("");
        txtNumeroDos.setText("");
        txtResultados.setText("");
        
        txtNumeroUno.requestFocusInWindow();
        cmbOperaciones.setSelectedIndex(0);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOperaciones;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumeroDos;
    private javax.swing.JTextField txtNumeroUno;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JTextField txtResultados;
    // End of variables declaration//GEN-END:variables
}
